# Generated by Django 3.2.5 on 2022-06-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220630_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loaction',
            new_name='location',
        ),
    ]
