# Generated by Django 3.2.5 on 2022-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_loaction_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user-default.png', null=True, upload_to='profile_images/'),
        ),
    ]
