# Generated by Django 3.2.5 on 2022-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user-default.png', null=True, upload_to='profile_images/'),
        ),
    ]
