# Generated by Django 3.2.5 on 2022-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20220627_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='ibraheem.jpg', null=True, upload_to=''),
        ),
    ]
