# Generated by Django 3.2.5 on 2022-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='basicapp/ib.jpg', null=True, upload_to=''),
        ),
    ]
