# Generated by Django 3.2.5 on 2022-07-04 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0016_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank='True', default='images/default.jpg', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
