# Generated by Django 3.2.5 on 2022-07-19 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0029_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank='True', default='project_images/default.jpg', null=True, upload_to='project_images/images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
