# Generated by Django 3.2.5 on 2022-07-19 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0038_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
